<?php

namespace App\Models;

use App\Scopes\MerchantScope;
use App\Scopes\ShopScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Schema;

class CommonModel extends Model
{
    use SoftDeletes;
    protected $is_show_ms=true;
    public static $merchant_id = 0;
    public static $shop_id = 0;
    public static $fields_status = ['删除','正常','禁用'];

//    protected $

    /*
     * 属性注入
     * */
    public function setAttribute($key, $value)
    {
        parent::setAttribute($key,$value);
//        dump($this->exists);exit; //表示  true编辑  和 false新增
        if($this->is_show_ms){
            $this->attributes['merchant_id'] = self::$merchant_id;
            $this->attributes['shop_id'] = self::$shop_id;
        }
    }

    public function fill(array $attributes)
    {
        if(!$this->fillable && $attributes){
            $this->fillable(Schema::getColumnListing($this->getTable()));
        }

        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }


    /**
     * 模型的“启动”方法.--注册全局查询对象
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new MerchantScope);
        static::addGlobalScope(new ShopScope);
    }
}
