<?php

namespace App\Models;

use App\Scopes\MerchantScope;
use App\Scopes\ShopScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Schema;

class CommonModel extends Model
{
    use SoftDeletes;

//    protected $


    public function fill(array $attributes)
    {
        if(!$this->fillable && $attributes){
            $this->fillable(Schema::getColumnListing($this->getTable()));
        }

        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }


    /**
     * 模型的“启动”方法.--注册全局查询对象
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new MerchantScope);
        static::addGlobalScope(new ShopScope);
    }
}
