<?php

namespace App\Models;


class GoodsAttrModel extends CommonModel
{
    //
    protected $table='goods_attr';

    public $timestamps = false;

    protected $casts = [
        'attr' => 'array',
    ];
    /*
     * test
     * */
//    public function category()
//    {
//        return $this->belongsTo('App\User','stock','id');
//    }


    protected static function boot($bind_merchant_bool=false)
    {
        parent::boot($bind_merchant_bool); // TODO: Change the autogenerated stub
    }


}
